[package]
name = "umap"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = { version = "6.1.0", features = ["rayon"] }
derive_builder = "0.20.2"
ndarray = "0.16.1"
rayon = "1.10.0"
sprs = "0.11.3"
